name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: volta-cli/action@v1

    - run: npm ci

    - run: npx lerna bootstrap --ci

    - run: npx lerna run test
